//creates bottom of snowman
polySphere -radius 3 -subdivisionsX 20 -subdivisionsY 20 -axis 0 1 0 -createUVs 2 -constructionHistory 1;
move -relative 0 3 0 ;

//creates middle sphere
polySphere -r 1 -sx 20 -sy 20 -ax 0 1 0 -cuv 2 -ch 1;
polySphere -e -radius 2;
move -relative 0 7 0 ;

//creates head sphere
polySphere -radius 1 -subdivisionsX 20 -subdivisionsY 20 -axis 0 1 0 -createUVs 2 -constructionHistory 1;
move -relative 0 9.5 0 ;